- name: install yum deps for arm!!!
  shell: dnf install -y python-urlgrabber pyxattr yum-metadata-parser
  when: ansible_distribution == "Fedora" and ansible_machine == "armv7l" and ansible_distribution_version|int >= 22

- name: install yum from Fedora 23 for arm!!!
  shell: dnf install -y https://kojipkgs.fedoraproject.org//packages/yum/3.4.3/506.fc23/noarch/yum-3.4.3-506.fc23.noarch.rpm
  when: ansible_distribution == "Fedora" and ansible_machine == "armv7l" and ansible_distribution_version|int >= 22

- name: install yum if it has been dropped from our distribution -- Fedora 22 uses dnf!!!
  shell: dnf install -y yum
  when: ansible_distribution == "Fedora" and ansible_distribution_version|int >= 22 and ansible_machine != "armv7l"

- name: Install yum packages
  package: name={{ item }}
           state=present
  with_items:
   - yum-utils
   - createrepo
  when: ansible_distribution != "Debian"
  tags:
    - download

- name: Create local yum repo
  shell: createrepo {{ yum_packages_dir }}
  when: ansible_distribution != "Debian"

- name: Install local repo file.
  template: dest=/etc/yum.repos.d/xsce-local.repo
            src=local.repo
            owner=root
            mode=0644
  when: ansible_distribution != "Debian"

- name: Install common packages
  package: name={{ item }}
           state=present
  with_items:
   - acpid
   - mlocate
   - rsync
   - htop
   - etckeeper
   - python-passlib
   - usbmount
   - net-tools
   - openssh-server
   - sudo
   - inetutils-syslogd
   - logrotate
#   - xml-common
   - make
   - tar
   - unzip
   - bzip2
   - i2c-tools
   - bridge-utils
   - usbutils
   - hostapd
   - wpasupplicant
   - wget
   - openssl   #FC 18 does not supply, but pear requires
#   - linux-firmware # grab wifi firmware--Debian installs non-free automatically
  tags:
    - download

- name: Update common packages
  package: name={{ item }}
           state=latest
  with_items:
   - network-manager
   - bash
   - iptables
#   - glibc # CVE-2015-7547
   - libc-bin
   - libc6
  tags:
    - download

- name: Install optional exFAT packages for CentOS
  shell: yum --enablerepo=li-nux-ro install exfat-utils fuse-exfat
  when: exFAT_enabled == "True" and ansible_distribution == "CentOS"

- name: Disable updating ejabberd on CentOS
  shell: sed -i -e '/^enabled=/a exclude=ejabberd' {{ item }}
  with_items:
    - /etc/yum.repos.d/CentOS-Base.repo
    - /etc/yum.repos.d/CentOS-CR.repo
    - /etc/yum.repos.d/CentOS-fasttrack.repo
    - /etc/yum.repos.d/CentOS-Vault.repo
  when: ansible_distribution == "CentOS"

